package view;

import control.ControleCadastro;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class ViewCadastro extends javax.swing.JFrame {
    ControleCadastro controleCadastro = new ControleCadastro();
    ArrayList<String> sintomas = new ArrayList();
    
    
    public ViewCadastro() {
        initComponents();
    }
    
    public void getSintomas(){
        
        sintomas.add(jComboBoxFebreDias.getSelectedItem().toString());
        sintomas.add(jComboBoxSubfebril.getSelectedItem().toString());
        sintomas.add(jComboBoxDorArticulacao.getSelectedItem().toString());
        sintomas.add(jComboBoxInchacoArticulacao.getSelectedItem().toString());
        sintomas.add(jComboBoxCoceira.getSelectedItem().toString());
        sintomas.add(jComboBoxInchacoGarganta.getSelectedItem().toString());
        sintomas.add(jComboBoxDorDeCabeca.getSelectedItem().toString());
        sintomas.add(jComboBoxManchaPele.getSelectedItem().toString());
        sintomas.add(jComboBoxDorCorpo.getSelectedItem().toString());
        sintomas.add(jComboBoxNauseaVomito.getSelectedItem().toString());
        sintomas.add(jComboBoxDorMuscular.getSelectedItem().toString());
        sintomas.add(jComboBoxFaltaApetite.getSelectedItem().toString());
        sintomas.add(jComboBoxConjuntivite.getSelectedItem().toString());        
        sintomas.add(jComboBoxCalafrios.getSelectedItem().toString());
        sintomas.add(jComboBoxTremores.getSelectedItem().toString());
        sintomas.add(jComboBoxFadigaFraqueza.getSelectedItem().toString());   
        sintomas.add(jComboBoxSudorese.getSelectedItem().toString());     
    }
    
    private void validaCampos() {
                
    if(verificaCampoNulo()){
        JOptionPane.showMessageDialog(this, "Preencha todos os campos.", "Aviso", JOptionPane.WARNING_MESSAGE);
    }else if (verificaEmail()){
        JOptionPane.showMessageDialog(this, "Insira um email válido.", "Aviso", JOptionPane.WARNING_MESSAGE);
    }else{
        realizaCadastro();
    }
}
    
    public boolean verificaCampoNulo(){
        return "".equals(jTextFieldNome.getText()) || "".equals(jTextFieldEndereco.getText())|| "".equals(jTextFieldCidade.getText())||  
               "".equals(jTextFieldCelular.getText()) || "".equals(jTextFieldEmail.getText());
}
    public boolean verificaEmail(){
    int cont = 0;
        for (int j = 0; j < jTextFieldEmail.getText().length(); j++) {
            if (jTextFieldEmail.getText().charAt(j) == '@') {
                cont++;
            }
        }
        return cont != 1;
}
    
    public void realizaCadastro(){
        
    //controleCadastro.salvarCadastro(jTextFieldNome.getText(), jTextFieldEndereco.getText(), jTextFieldCidade.getText(), jTextFieldCelular.getText(), jTextFieldEmail.getText());
    JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso.");
                
    this.dispose();
    
    jTextFieldNome.setText("");
    jTextFieldEndereco.setText("");
    jTextFieldCidade.setText("");
    jTextFieldCelular.setText("");
    jTextFieldEmail.setText("");
    
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelCadastro = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JFormattedTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelFormulario = new javax.swing.JPanel();
        jLabelPreencherFormulario = new javax.swing.JLabel();
        jLabelFebreDias = new javax.swing.JLabel();
        jComboBoxInchacoArticulacao = new javax.swing.JComboBox();
        jButtonSalvar = new javax.swing.JButton();
        jLabelDorArticulacao = new javax.swing.JLabel();
        jComboBoxSubfebril = new javax.swing.JComboBox();
        jLabelInchacoArticulacao = new javax.swing.JLabel();
        jComboBoxFebreDias = new javax.swing.JComboBox();
        jLabelFebre = new javax.swing.JLabel();
        jComboBoxDorArticulacao = new javax.swing.JComboBox();
        jLabelDorDeCabeca = new javax.swing.JLabel();
        jComboBoxInchacoGarganta = new javax.swing.JComboBox();
        jLabelCoceira = new javax.swing.JLabel();
        jComboBoxCoceira = new javax.swing.JComboBox();
        jLabelInchacoGarganta1 = new javax.swing.JLabel();
        jComboBoxDorDeCabeca = new javax.swing.JComboBox();
        jLabelFaltaApetite = new javax.swing.JLabel();
        jComboBoxManchaPele = new javax.swing.JComboBox();
        jLabelManchaPele = new javax.swing.JLabel();
        jComboBoxDorCorpo = new javax.swing.JComboBox();
        jLabelDorCorpo = new javax.swing.JLabel();
        jComboBoxNauseaVomito = new javax.swing.JComboBox();
        jLabelNauseaVomito = new javax.swing.JLabel();
        jComboBoxDorMuscular = new javax.swing.JComboBox();
        jLabelDorMuscular = new javax.swing.JLabel();
        jComboBoxFaltaApetite = new javax.swing.JComboBox();
        jLabelConjuntivite = new javax.swing.JLabel();
        jComboBoxConjuntivite = new javax.swing.JComboBox();
        jComboBoxTremores = new javax.swing.JComboBox();
        jLabelCalafrios = new javax.swing.JLabel();
        jComboBoxCalafrios = new javax.swing.JComboBox();
        jLabelTremores = new javax.swing.JLabel();
        jComboBoxFadigaFraqueza = new javax.swing.JComboBox();
        jLabelFadigaFraqueza = new javax.swing.JLabel();
        jComboBoxSudorese = new javax.swing.JComboBox();
        jLabelSudorese = new javax.swing.JLabel();
        jLabelSubFebril = new javax.swing.JLabel();
        jComboBoxFebre = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro do usuário");
        setPreferredSize(new java.awt.Dimension(406, 500));
        setResizable(false);

        jPanelPrincipal.setBackground(new java.awt.Color(50, 0, 130));
        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jPanelCadastro.setBackground(new java.awt.Color(22, 35, 87));

        jLabelNome.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome:");

        jLabelEndereco.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelEndereco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEndereco.setText("Endereço:");

        jLabelCidade.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelCidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCidade.setText("Cidade:");

        jLabelCelular.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelCelular.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCelular.setText("Celular:");

        jLabelEmail.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email:");

        try {
            jTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("Avançar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEndereco)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelCidade)
                            .addComponent(jLabelCelular)
                            .addComponent(jLabelEmail))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jTextFieldEndereco)
                            .addComponent(jTextFieldCidade)
                            .addComponent(jTextFieldEmail))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCelular)
                    .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );

        jPanelPrincipal.add(jPanelCadastro, "cadastro");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelFormulario.setBackground(new java.awt.Color(22, 35, 87));
        jPanelFormulario.setPreferredSize(new java.awt.Dimension(415, 1200));

        jLabelPreencherFormulario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelPreencherFormulario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPreencherFormulario.setText("Responda o Questionário:");

        jLabelFebreDias.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelFebreDias.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFebreDias.setText("Você sente febre a quantos dias?");

        jComboBoxInchacoArticulacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim, leve", "Sim, intensa" }));
        jComboBoxInchacoArticulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInchacoArticulacaoActionPerformed(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabelDorArticulacao.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelDorArticulacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDorArticulacao.setText("Você sente dores nas articulações?");

        jComboBoxSubfebril.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0 dias", "1 dia", "2 dias" }));
        jComboBoxSubfebril.setEnabled(false);
        jComboBoxSubfebril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSubfebrilActionPerformed(evt);
            }
        });

        jLabelInchacoArticulacao.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelInchacoArticulacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInchacoArticulacao.setText("Você apresenta algum tipo de inchaço nas articulações?");

        jComboBoxFebreDias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0 dias", "1 dia", "2 dias", "3 dias", "4 dias", "5 dias", "6 dias", "7 dias" }));
        jComboBoxFebreDias.setEnabled(false);
        jComboBoxFebreDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFebreDiasActionPerformed(evt);
            }
        });

        jLabelFebre.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelFebre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFebre.setText("Você sente febre?");

        jComboBoxDorArticulacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim, leve", "Sim, moderada", "Sim, intensa" }));
        jComboBoxDorArticulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDorArticulacaoActionPerformed(evt);
            }
        });

        jLabelDorDeCabeca.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelDorDeCabeca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDorDeCabeca.setText("Você sente dor de cabeça?");

        jComboBoxInchacoGarganta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim, leve", "Sim, moderada", "Sim, intensa" }));
        jComboBoxInchacoGarganta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInchacoGargantaActionPerformed(evt);
            }
        });

        jLabelCoceira.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelCoceira.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoceira.setText("Você sente coceira?");

        jComboBoxCoceira.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim, leve", "Sim, moderada", "Sim, intensa" }));
        jComboBoxCoceira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCoceiraActionPerformed(evt);
            }
        });

        jLabelInchacoGarganta1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelInchacoGarganta1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInchacoGarganta1.setText("Você apresenta inchaço na garganta?");

        jComboBoxDorDeCabeca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim, moderada", "Sim, intensa" }));
        jComboBoxDorDeCabeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDorDeCabecaActionPerformed(evt);
            }
        });

        jLabelFaltaApetite.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelFaltaApetite.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFaltaApetite.setText("Você apresenta falta de apetite?");

        jComboBoxManchaPele.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));
        jComboBoxManchaPele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxManchaPeleActionPerformed(evt);
            }
        });

        jLabelManchaPele.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelManchaPele.setForeground(new java.awt.Color(255, 255, 255));
        jLabelManchaPele.setText("Você apresenta manchas na pele?");

        jComboBoxDorCorpo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));
        jComboBoxDorCorpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDorCorpoActionPerformed(evt);
            }
        });

        jLabelDorCorpo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelDorCorpo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDorCorpo.setText("Você sente dor no corpo?");

        jComboBoxNauseaVomito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));
        jComboBoxNauseaVomito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNauseaVomitoActionPerformed(evt);
            }
        });

        jLabelNauseaVomito.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelNauseaVomito.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNauseaVomito.setText("Você apresenta náuseas ou vômitos?");

        jComboBoxDorMuscular.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));
        jComboBoxDorMuscular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDorMuscularActionPerformed(evt);
            }
        });

        jLabelDorMuscular.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelDorMuscular.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDorMuscular.setText("Você apresenta dor muscular?");

        jComboBoxFaltaApetite.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));
        jComboBoxFaltaApetite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFaltaApetiteActionPerformed(evt);
            }
        });

        jLabelConjuntivite.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelConjuntivite.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConjuntivite.setText("Você apresenta conjuntivite?");

        jComboBoxConjuntivite.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));
        jComboBoxConjuntivite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConjuntiviteActionPerformed(evt);
            }
        });

        jComboBoxTremores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));

        jLabelCalafrios.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelCalafrios.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCalafrios.setText("Você apresenta calafrios?");

        jComboBoxCalafrios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));
        jComboBoxCalafrios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCalafriosActionPerformed(evt);
            }
        });

        jLabelTremores.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelTremores.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTremores.setText("Você apresenta tremores?");

        jComboBoxFadigaFraqueza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));
        jComboBoxFadigaFraqueza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFadigaFraquezaActionPerformed(evt);
            }
        });

        jLabelFadigaFraqueza.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelFadigaFraqueza.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFadigaFraqueza.setText("Você apresenta fadiga ou fraqueza?");

        jComboBoxSudorese.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim" }));
        jComboBoxSudorese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSudoreseActionPerformed(evt);
            }
        });

        jLabelSudorese.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelSudorese.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSudorese.setText("Você tem transpirado em excesso?");

        jLabelSubFebril.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelSubFebril.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubFebril.setText("A quantos dias você apresenta o estado subfebriel?");

        jComboBoxFebre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não", "Sim, leve", "Sim, moderada" }));
        jComboBoxFebre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFebreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormularioLayout = new javax.swing.GroupLayout(jPanelFormulario);
        jPanelFormulario.setLayout(jPanelFormularioLayout);
        jPanelFormularioLayout.setHorizontalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxFebre, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxInchacoGarganta, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDorArticulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFebreDias, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxSubfebril, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFormularioLayout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLabelPreencherFormulario))
                        .addComponent(jLabelFebreDias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDorArticulacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxInchacoArticulacao, 0, 350, Short.MAX_VALUE))
                    .addComponent(jLabelInchacoArticulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFebre, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDorDeCabeca, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCoceira, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCoceira, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInchacoGarganta1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDorDeCabeca, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFaltaApetite, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxManchaPele, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelManchaPele, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDorCorpo, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDorCorpo, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNauseaVomito, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNauseaVomito, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDorMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDorMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFaltaApetite, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConjuntivite, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTremores, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCalafrios, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCalafrios, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTremores, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFadigaFraqueza, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFadigaFraqueza, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSudorese, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSubFebril, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxConjuntivite, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonSalvar)
                        .addComponent(jComboBoxSudorese, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanelFormularioLayout.setVerticalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPreencherFormulario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFebre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFebre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSubFebril, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSubfebril, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFebreDias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFebreDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDorArticulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDorArticulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInchacoArticulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxInchacoArticulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabelCoceira, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCoceira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInchacoGarganta1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxInchacoGarganta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDorDeCabeca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDorDeCabeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelManchaPele, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxManchaPele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDorCorpo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDorCorpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNauseaVomito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxNauseaVomito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDorMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDorMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFaltaApetite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFaltaApetite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConjuntivite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxConjuntivite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCalafrios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCalafrios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTremores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTremores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFadigaFraqueza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFadigaFraqueza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSudorese, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSudorese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanelFormulario);

        jPanelPrincipal.add(jScrollPane1, "formulario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(412, 481));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout layout = (CardLayout) jPanelPrincipal.getLayout();
        layout.show(jPanelPrincipal, "formulario");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        getSintomas();
        ControleCadastro c = new ControleCadastro();
        c.executaProLog(sintomas);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxInchacoArticulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInchacoArticulacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxInchacoArticulacaoActionPerformed

    private void jComboBoxSubfebrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSubfebrilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSubfebrilActionPerformed

    private void jComboBoxFebreDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFebreDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFebreDiasActionPerformed

    private void jComboBoxDorArticulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDorArticulacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDorArticulacaoActionPerformed

    private void jComboBoxInchacoGargantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInchacoGargantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxInchacoGargantaActionPerformed

    private void jComboBoxCoceiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCoceiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCoceiraActionPerformed

    private void jComboBoxDorDeCabecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDorDeCabecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDorDeCabecaActionPerformed

    private void jComboBoxManchaPeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxManchaPeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxManchaPeleActionPerformed

    private void jComboBoxDorCorpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDorCorpoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDorCorpoActionPerformed

    private void jComboBoxNauseaVomitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNauseaVomitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNauseaVomitoActionPerformed

    private void jComboBoxDorMuscularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDorMuscularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDorMuscularActionPerformed

    private void jComboBoxFaltaApetiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFaltaApetiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFaltaApetiteActionPerformed

    private void jComboBoxConjuntiviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConjuntiviteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxConjuntiviteActionPerformed

    private void jComboBoxCalafriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCalafriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCalafriosActionPerformed

    private void jComboBoxFadigaFraquezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFadigaFraquezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFadigaFraquezaActionPerformed

    private void jComboBoxSudoreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSudoreseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSudoreseActionPerformed

    private void jComboBoxFebreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFebreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFebreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxCalafrios;
    private javax.swing.JComboBox jComboBoxCoceira;
    private javax.swing.JComboBox jComboBoxConjuntivite;
    private javax.swing.JComboBox jComboBoxDorArticulacao;
    private javax.swing.JComboBox jComboBoxDorCorpo;
    private javax.swing.JComboBox jComboBoxDorDeCabeca;
    private javax.swing.JComboBox jComboBoxDorMuscular;
    private javax.swing.JComboBox jComboBoxFadigaFraqueza;
    private javax.swing.JComboBox jComboBoxFaltaApetite;
    private javax.swing.JComboBox jComboBoxFebre;
    private javax.swing.JComboBox jComboBoxFebreDias;
    private javax.swing.JComboBox jComboBoxInchacoArticulacao;
    private javax.swing.JComboBox jComboBoxInchacoGarganta;
    private javax.swing.JComboBox jComboBoxManchaPele;
    private javax.swing.JComboBox jComboBoxNauseaVomito;
    private javax.swing.JComboBox jComboBoxSubfebril;
    private javax.swing.JComboBox jComboBoxSudorese;
    private javax.swing.JComboBox jComboBoxTremores;
    private javax.swing.JLabel jLabelCalafrios;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCoceira;
    private javax.swing.JLabel jLabelConjuntivite;
    private javax.swing.JLabel jLabelDorArticulacao;
    private javax.swing.JLabel jLabelDorCorpo;
    private javax.swing.JLabel jLabelDorDeCabeca;
    private javax.swing.JLabel jLabelDorMuscular;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelFadigaFraqueza;
    private javax.swing.JLabel jLabelFaltaApetite;
    private javax.swing.JLabel jLabelFebre;
    private javax.swing.JLabel jLabelFebreDias;
    private javax.swing.JLabel jLabelInchacoArticulacao;
    private javax.swing.JLabel jLabelInchacoGarganta1;
    private javax.swing.JLabel jLabelManchaPele;
    private javax.swing.JLabel jLabelNauseaVomito;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPreencherFormulario;
    private javax.swing.JLabel jLabelSubFebril;
    private javax.swing.JLabel jLabelSudorese;
    private javax.swing.JLabel jLabelTremores;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
